[tool.poetry]
name = "my-deps"
version = "1.0.0"
description = "mine"
authors = ["ikeikeikeike <jp.ne.co.jp@gmail.com>"]

[tool.poetry.dependencies]
python = "==3.9.6"
PyYAML = "^5.4"
botocore = "^1.27"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
