[tool.poetry]
name = "my-deps"
version = "1.0.0"
description = "mine"
authors = ["ikeikeikeike <jp.ne.co.jp@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.7"
PyYAML = "^5.4"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
